function init(backPage){	
	mousePlot(backPage.loggerPack);
	//The mouseplot was generated by the mousePlot script
	//Saving using the library saveSvgAsPng
	saveSvgAsPng(document.getElementsByTagName("svg")[0], "mouseplot.png", {backgroundColor: 'white'}).then(function(e){console.log('done');}, function(e){});
	
	//myPort.postMessage({done: 1});
}

var background = browser.runtime.getBackgroundPage();

var myPort = browser.runtime.connect({name:"port-from-download"});

background.then(init);

