//Previously, the heatmap was generated by the report script
//Saving using the library saveSvgAsPng
saveSvgAsPng(document.getElementsByTagName("svg")[0], "heatmap.png", {backgroundColor: 'white'});
window.close();