//Previously, the mouseplot was generated by the report script
//Saving using the library saveSvgAsPng
saveSvgAsPng(document.getElementsByTagName("svg")[0], "mouseplot.png", {backgroundColor: 'white'});
window.close();