function init(backPage){
	heatMap(backPage.loggerPack);	
	//The heatmap was generated by the heatmap script
	//Saving using the library saveSvgAsPng
	saveSvgAsPng(document.getElementsByTagName("svg")[0], "heatmap.png", {backgroundColor: 'white'});
}

var background = browser.runtime.getBackgroundPage();

var myPort = browser.runtime.connect({name:"port-from-download"});

background.then(init);
